services:
  node-app:
    image: node-app:latest
    build:
      dockerfile:Dockerfile
    restart: always
    volumes:
      - ./:/var/www
    ports:
      - "6950:6950"
    networks:
      - database
  mongo:
    image: mongo
    volumes:
      - "./mongo/data:/data/db"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - database

networks:
  database:
    driver: bridge

